# Generated by Django 5.0.1 on 2024-02-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.IntegerField(default=10000),
        ),
    ]
